"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    delete_v2_objects_object_op as models_delete_v2_objects_object_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class DeleteV2ObjectsObjectNotFoundErrorData(BaseModel):
    status_code: float
    type: models_delete_v2_objects_object_op.DeleteV2ObjectsObjectNotFoundType
    code: models_delete_v2_objects_object_op.DeleteV2ObjectsObjectNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class DeleteV2ObjectsObjectNotFoundError(SDKError):
    r"""Not Found"""

    data: DeleteV2ObjectsObjectNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: DeleteV2ObjectsObjectNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class DeleteV2ObjectsObjectUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_delete_v2_objects_object_op.DeleteV2ObjectsObjectForbiddenType
    code: models_delete_v2_objects_object_op.DeleteV2ObjectsObjectCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class DeleteV2ObjectsObjectUnauthorizedError(SDKError):
    r"""Forbidden"""

    data: DeleteV2ObjectsObjectUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: DeleteV2ObjectsObjectUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class DeleteV2ObjectsObjectSystemEditUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_delete_v2_objects_object_op.DeleteV2ObjectsObjectBadRequestType
    code: models_delete_v2_objects_object_op.DeleteV2ObjectsObjectCodeSystemEditUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class DeleteV2ObjectsObjectSystemEditUnauthorizedError(SDKError):
    r"""Bad Request"""

    data: DeleteV2ObjectsObjectSystemEditUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: DeleteV2ObjectsObjectSystemEditUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
