"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    delete_v2_activities_activity_op as models_delete_v2_activities_activity_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class DeleteV2ActivitiesActivityNotFoundErrorData(BaseModel):
    status_code: float
    type: models_delete_v2_activities_activity_op.DeleteV2ActivitiesActivityNotFoundType
    code: models_delete_v2_activities_activity_op.DeleteV2ActivitiesActivityNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class DeleteV2ActivitiesActivityNotFoundError(SDKError):
    r"""Not Found"""

    data: DeleteV2ActivitiesActivityNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: DeleteV2ActivitiesActivityNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class DeleteV2ActivitiesActivitySystemEditUnauthorizedErrorData(BaseModel):
    status_code: float
    type: (
        models_delete_v2_activities_activity_op.DeleteV2ActivitiesActivityBadRequestType
    )
    code: models_delete_v2_activities_activity_op.DeleteV2ActivitiesActivityCodeSystemEditUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class DeleteV2ActivitiesActivitySystemEditUnauthorizedError(SDKError):
    r"""Bad Request"""

    data: DeleteV2ActivitiesActivitySystemEditUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: DeleteV2ActivitiesActivitySystemEditUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
