"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    delete_v2_objects_object_records_record_id_op as models_delete_v2_objects_object_records_record_id_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class DeleteV2ObjectsObjectRecordsRecordIDNotFoundErrorData(BaseModel):
    status_code: float
    type: models_delete_v2_objects_object_records_record_id_op.DeleteV2ObjectsObjectRecordsRecordIDNotFoundType
    code: models_delete_v2_objects_object_records_record_id_op.DeleteV2ObjectsObjectRecordsRecordIDNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class DeleteV2ObjectsObjectRecordsRecordIDNotFoundError(SDKError):
    r"""Not Found"""

    data: DeleteV2ObjectsObjectRecordsRecordIDNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: DeleteV2ObjectsObjectRecordsRecordIDNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class DeleteV2ObjectsObjectRecordsRecordIDUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_delete_v2_objects_object_records_record_id_op.DeleteV2ObjectsObjectRecordsRecordIDForbiddenType
    code: models_delete_v2_objects_object_records_record_id_op.DeleteV2ObjectsObjectRecordsRecordIDCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class DeleteV2ObjectsObjectRecordsRecordIDUnauthorizedError(SDKError):
    r"""Forbidden"""

    data: DeleteV2ObjectsObjectRecordsRecordIDUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: DeleteV2ObjectsObjectRecordsRecordIDUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
