"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    patch_v2_target_identifier_attributes_attribute_statuses_status_op as models_patch_v2_target_identifier_attributes_attribute_statuses_status_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData(
    BaseModel
):
    status_code: float
    type: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusConflictType
    code: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusCodeSlugConflict
    message: str


@dataclass(unsafe_hash=True)
class PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictError(
    SDKError
):
    r"""Conflict"""

    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData(
    BaseModel
):
    status_code: float
    type: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundType
    code: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundError(SDKError):
    r"""Not Found"""

    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData = (
        field(hash=False)
    )

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusUnauthorizedErrorData(
    BaseModel
):
    status_code: float
    type: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusForbiddenType
    code: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PatchV2TargetIdentifierAttributesAttributeStatusesStatusUnauthorizedError(
    SDKError
):
    r"""Forbidden"""

    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusUnauthorizedErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData(
    BaseModel
):
    status_code: float
    type: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusBadRequestType
    code: models_patch_v2_target_identifier_attributes_attribute_statuses_status_op.PatchV2TargetIdentifierAttributesAttributeStatusesStatusBadRequestCode
    message: str


@dataclass(unsafe_hash=True)
class PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError(
    SDKError
):
    r"""Bad Request"""

    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
