"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    patch_v2_target_identifier_attributes_attribute_op as models_patch_v2_target_identifier_attributes_attribute_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PatchV2TargetIdentifierAttributesAttributeNotFoundErrorData(BaseModel):
    status_code: float
    type: models_patch_v2_target_identifier_attributes_attribute_op.PatchV2TargetIdentifierAttributesAttributeNotFoundType
    code: models_patch_v2_target_identifier_attributes_attribute_op.PatchV2TargetIdentifierAttributesAttributeNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PatchV2TargetIdentifierAttributesAttributeNotFoundError(SDKError):
    r"""Not Found"""

    data: PatchV2TargetIdentifierAttributesAttributeNotFoundErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PatchV2TargetIdentifierAttributesAttributeUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_patch_v2_target_identifier_attributes_attribute_op.PatchV2TargetIdentifierAttributesAttributeForbiddenType
    code: models_patch_v2_target_identifier_attributes_attribute_op.PatchV2TargetIdentifierAttributesAttributeCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PatchV2TargetIdentifierAttributesAttributeUnauthorizedError(SDKError):
    r"""Forbidden"""

    data: PatchV2TargetIdentifierAttributesAttributeUnauthorizedErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PatchV2TargetIdentifierAttributesAttributeSystemEditUnauthorizedErrorData(
    BaseModel
):
    status_code: float
    type: models_patch_v2_target_identifier_attributes_attribute_op.PatchV2TargetIdentifierAttributesAttributeBadRequestType
    code: models_patch_v2_target_identifier_attributes_attribute_op.PatchV2TargetIdentifierAttributesAttributeCodeSystemEditUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PatchV2TargetIdentifierAttributesAttributeSystemEditUnauthorizedError(SDKError):
    r"""Bad Request"""

    data: PatchV2TargetIdentifierAttributesAttributeSystemEditUnauthorizedErrorData = (
        field(hash=False)
    )

    def __init__(
        self,
        data: PatchV2TargetIdentifierAttributesAttributeSystemEditUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
