"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    post_v2_sequences_unsubscribed_emailsop as models_post_v2_sequences_unsubscribed_emailsop,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
import pydantic
from typing import Optional
from typing_extensions import Annotated


class PostV2SequencesUnsubscribedEmailsValidationTypeErrorData(BaseModel):
    status_code: Annotated[float, pydantic.Field(alias="statusCode")]
    type: models_post_v2_sequences_unsubscribed_emailsop.PostV2SequencesUnsubscribedEmailsType
    code: models_post_v2_sequences_unsubscribed_emailsop.PostV2SequencesUnsubscribedEmailsCode
    message: str


@dataclass(unsafe_hash=True)
class PostV2SequencesUnsubscribedEmailsValidationTypeError(SDKError):
    r"""Bad Request"""

    data: PostV2SequencesUnsubscribedEmailsValidationTypeErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2SequencesUnsubscribedEmailsValidationTypeErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
