"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import post_v2_objectsop as models_post_v2_objectsop
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PostV2ObjectsSlugConflictErrorData(BaseModel):
    status_code: float
    type: models_post_v2_objectsop.PostV2ObjectsConflictType
    code: models_post_v2_objectsop.PostV2ObjectsCodeSlugConflict
    message: str


@dataclass(unsafe_hash=True)
class PostV2ObjectsSlugConflictError(SDKError):
    r"""Conflict"""

    data: PostV2ObjectsSlugConflictErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ObjectsSlugConflictErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PostV2ObjectsUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_post_v2_objectsop.PostV2ObjectsForbiddenType
    code: models_post_v2_objectsop.PostV2ObjectsCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PostV2ObjectsUnauthorizedError(SDKError):
    r"""Forbidden"""

    data: PostV2ObjectsUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ObjectsUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class QuotaExceededErrorData(BaseModel):
    status_code: float
    type: models_post_v2_objectsop.PostV2ObjectsBadRequestType
    code: models_post_v2_objectsop.PostV2ObjectsCodeQuotaExceeded
    message: str


@dataclass(unsafe_hash=True)
class QuotaExceededError(SDKError):
    r"""Bad Request"""

    data: QuotaExceededErrorData = field(hash=False)

    def __init__(
        self,
        data: QuotaExceededErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
