"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    post_v2_objects_object_records_mergeop as models_post_v2_objects_object_records_mergeop,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PostV2ObjectsObjectRecordsMergeInvalidRequestErrorData(BaseModel):
    status_code: float
    type: models_post_v2_objects_object_records_mergeop.PostV2ObjectsObjectRecordsMergeNotFoundType
    code: models_post_v2_objects_object_records_mergeop.PostV2ObjectsObjectRecordsMergeCodeUnion
    message: str


@dataclass(unsafe_hash=True)
class PostV2ObjectsObjectRecordsMergeInvalidRequestError(SDKError):
    r"""Not Found"""

    data: PostV2ObjectsObjectRecordsMergeInvalidRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ObjectsObjectRecordsMergeInvalidRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PostV2ObjectsObjectRecordsMergeUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_post_v2_objects_object_records_mergeop.PostV2ObjectsObjectRecordsMergeForbiddenType
    code: models_post_v2_objects_object_records_mergeop.PostV2ObjectsObjectRecordsMergeCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PostV2ObjectsObjectRecordsMergeUnauthorizedError(SDKError):
    r"""Forbidden"""

    data: PostV2ObjectsObjectRecordsMergeUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ObjectsObjectRecordsMergeUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class SelfMergeErrorData(BaseModel):
    status_code: float
    type: models_post_v2_objects_object_records_mergeop.PostV2ObjectsObjectRecordsMergeBadRequestType
    code: models_post_v2_objects_object_records_mergeop.CodeSelfMerge
    message: str


@dataclass(unsafe_hash=True)
class SelfMergeError(SDKError):
    r"""Bad Request"""

    data: SelfMergeErrorData = field(hash=False)

    def __init__(
        self,
        data: SelfMergeErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
