"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import post_v2_activitiesop as models_post_v2_activitiesop
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PostV2ActivitiesSlugConflictErrorData(BaseModel):
    status_code: float
    type: models_post_v2_activitiesop.PostV2ActivitiesConflictType
    code: models_post_v2_activitiesop.PostV2ActivitiesCodeSlugConflict
    message: str


@dataclass(unsafe_hash=True)
class PostV2ActivitiesSlugConflictError(SDKError):
    r"""Conflict"""

    data: PostV2ActivitiesSlugConflictErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ActivitiesSlugConflictErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PostV2ActivitiesAuthErrorData(BaseModel):
    status_code: float
    type: models_post_v2_activitiesop.PostV2ActivitiesForbiddenType
    code: models_post_v2_activitiesop.PostV2ActivitiesCodeUnion
    message: str


@dataclass(unsafe_hash=True)
class PostV2ActivitiesAuthError(SDKError):
    r"""Forbidden"""

    data: PostV2ActivitiesAuthErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ActivitiesAuthErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
