"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    post_v2_activities_activity_recordsop as models_post_v2_activities_activity_recordsop,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PostV2ActivitiesActivityRecordsNotFoundErrorData(BaseModel):
    status_code: float
    type: models_post_v2_activities_activity_recordsop.PostV2ActivitiesActivityRecordsNotFoundType
    code: models_post_v2_activities_activity_recordsop.PostV2ActivitiesActivityRecordsNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PostV2ActivitiesActivityRecordsNotFoundError(SDKError):
    r"""Not Found"""

    data: PostV2ActivitiesActivityRecordsNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ActivitiesActivityRecordsNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PostV2ActivitiesActivityRecordsUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_post_v2_activities_activity_recordsop.PostV2ActivitiesActivityRecordsForbiddenType
    code: models_post_v2_activities_activity_recordsop.PostV2ActivitiesActivityRecordsCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PostV2ActivitiesActivityRecordsUnauthorizedError(SDKError):
    r"""Forbidden"""

    data: PostV2ActivitiesActivityRecordsUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ActivitiesActivityRecordsUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ValueNotFoundErrorData(BaseModel):
    status_code: float
    type: models_post_v2_activities_activity_recordsop.PostV2ActivitiesActivityRecordsBadRequestType
    code: models_post_v2_activities_activity_recordsop.PostV2ActivitiesActivityRecordsCodeValueNotFound
    message: str


@dataclass(unsafe_hash=True)
class ValueNotFoundError(SDKError):
    r"""Bad Request"""

    data: ValueNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: ValueNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
