"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    put_v2_meetings_meeting_id_op as models_put_v2_meetings_meeting_id_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PutV2MeetingsMeetingIDNotFoundErrorData(BaseModel):
    status_code: float
    type: models_put_v2_meetings_meeting_id_op.PutV2MeetingsMeetingIDNotFoundType
    code: models_put_v2_meetings_meeting_id_op.PutV2MeetingsMeetingIDNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PutV2MeetingsMeetingIDNotFoundError(SDKError):
    r"""Not Found"""

    data: PutV2MeetingsMeetingIDNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2MeetingsMeetingIDNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2MeetingsMeetingIDInvalidRequestErrorData(BaseModel):
    status_code: float
    type: models_put_v2_meetings_meeting_id_op.PutV2MeetingsMeetingIDBadRequestType
    code: models_put_v2_meetings_meeting_id_op.PutV2MeetingsMeetingIDCodeUnion
    message: str


@dataclass(unsafe_hash=True)
class PutV2MeetingsMeetingIDInvalidRequestError(SDKError):
    r"""Bad Request"""

    data: PutV2MeetingsMeetingIDInvalidRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2MeetingsMeetingIDInvalidRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
