"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    put_v2_objects_object_records_record_id_attributes_attribute_valuesop as models_put_v2_objects_object_records_record_id_attributes_attribute_valuesop,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundInvalidRequestErrorData(
    BaseModel
):
    status_code: float
    type: models_put_v2_objects_object_records_record_id_attributes_attribute_valuesop.PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundType
    code: models_put_v2_objects_object_records_record_id_attributes_attribute_valuesop.PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundInvalidRequestError(
    SDKError
):
    r"""Not Found"""

    data: PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundInvalidRequestErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundInvalidRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesUnauthorizedErrorData(
    BaseModel
):
    status_code: float
    type: models_put_v2_objects_object_records_record_id_attributes_attribute_valuesop.PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesForbiddenType
    code: models_put_v2_objects_object_records_record_id_attributes_attribute_valuesop.PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesUnauthorizedError(
    SDKError
):
    r"""Forbidden"""

    data: PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesUnauthorizedErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesBadRequestInvalidRequestErrorData(
    BaseModel
):
    status_code: float
    type: models_put_v2_objects_object_records_record_id_attributes_attribute_valuesop.PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesBadRequestType
    code: models_put_v2_objects_object_records_record_id_attributes_attribute_valuesop.PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesBadRequestCode
    message: str


@dataclass(unsafe_hash=True)
class PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesBadRequestInvalidRequestError(
    SDKError
):
    r"""Bad Request"""

    data: PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesBadRequestInvalidRequestErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PutV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesBadRequestInvalidRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
