"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    put_v2_lists_list_entriesop as models_put_v2_lists_list_entriesop,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PutV2ListsListEntriesNotFoundErrorData(BaseModel):
    status_code: float
    type: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesNotFoundType
    code: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PutV2ListsListEntriesNotFoundError(SDKError):
    r"""Not Found"""

    data: PutV2ListsListEntriesNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2ListsListEntriesNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ListsListEntriesUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesForbiddenType
    code: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PutV2ListsListEntriesUnauthorizedError(SDKError):
    r"""Forbidden"""

    data: PutV2ListsListEntriesUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2ListsListEntriesUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ListsListEntriesInvalidRequestErrorData(BaseModel):
    status_code: float
    type: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesBadRequestType
    code: models_put_v2_lists_list_entriesop.PutV2ListsListEntriesCodeUnion
    message: str


@dataclass(unsafe_hash=True)
class PutV2ListsListEntriesInvalidRequestError(SDKError):
    r"""Bad Request"""

    data: PutV2ListsListEntriesInvalidRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2ListsListEntriesInvalidRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
