"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    put_v2_activities_activity_recordsop as models_put_v2_activities_activity_recordsop,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PutV2ActivitiesActivityRecordsConcurrentWriteConflictErrorData(BaseModel):
    status_code: float
    type: models_put_v2_activities_activity_recordsop.PutV2ActivitiesActivityRecordsConflictType
    code: models_put_v2_activities_activity_recordsop.PutV2ActivitiesActivityRecordsCodeConcurrentWriteConflict
    message: str


@dataclass(unsafe_hash=True)
class PutV2ActivitiesActivityRecordsConcurrentWriteConflictError(SDKError):
    r"""Conflict"""

    data: PutV2ActivitiesActivityRecordsConcurrentWriteConflictErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PutV2ActivitiesActivityRecordsConcurrentWriteConflictErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ActivitiesActivityRecordsNotFoundErrorData(BaseModel):
    status_code: float
    type: models_put_v2_activities_activity_recordsop.PutV2ActivitiesActivityRecordsNotFoundType
    code: models_put_v2_activities_activity_recordsop.PutV2ActivitiesActivityRecordsNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PutV2ActivitiesActivityRecordsNotFoundError(SDKError):
    r"""Not Found"""

    data: PutV2ActivitiesActivityRecordsNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2ActivitiesActivityRecordsNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ActivitiesActivityRecordsAuthErrorData(BaseModel):
    status_code: float
    type: models_put_v2_activities_activity_recordsop.PutV2ActivitiesActivityRecordsForbiddenType
    code: models_put_v2_activities_activity_recordsop.PutV2ActivitiesActivityRecordsForbiddenCodeUnion
    message: str


@dataclass(unsafe_hash=True)
class PutV2ActivitiesActivityRecordsAuthError(SDKError):
    r"""Forbidden"""

    data: PutV2ActivitiesActivityRecordsAuthErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2ActivitiesActivityRecordsAuthErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ActivitiesActivityRecordsInvalidRequestErrorData(BaseModel):
    status_code: float
    type: models_put_v2_activities_activity_recordsop.PutV2ActivitiesActivityRecordsBadRequestType
    code: models_put_v2_activities_activity_recordsop.PutV2ActivitiesActivityRecordsBadRequestCode
    message: str


@dataclass(unsafe_hash=True)
class PutV2ActivitiesActivityRecordsInvalidRequestError(SDKError):
    r"""Bad Request"""

    data: PutV2ActivitiesActivityRecordsInvalidRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2ActivitiesActivityRecordsInvalidRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
