"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    put_v2_activities_activity_records_record_id_op as models_put_v2_activities_activity_records_record_id_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PutV2ActivitiesActivityRecordsRecordIDNotFoundErrorData(BaseModel):
    status_code: float
    type: models_put_v2_activities_activity_records_record_id_op.PutV2ActivitiesActivityRecordsRecordIDNotFoundType
    code: models_put_v2_activities_activity_records_record_id_op.PutV2ActivitiesActivityRecordsRecordIDNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PutV2ActivitiesActivityRecordsRecordIDNotFoundError(SDKError):
    r"""Not Found"""

    data: PutV2ActivitiesActivityRecordsRecordIDNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PutV2ActivitiesActivityRecordsRecordIDNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData(BaseModel):
    status_code: float
    type: models_put_v2_activities_activity_records_record_id_op.PutV2ActivitiesActivityRecordsRecordIDForbiddenType
    code: models_put_v2_activities_activity_records_record_id_op.PutV2ActivitiesActivityRecordsRecordIDCodeUnauthorized
    message: str


@dataclass(unsafe_hash=True)
class PutV2ActivitiesActivityRecordsRecordIDUnauthorizedError(SDKError):
    r"""Forbidden"""

    data: PutV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PutV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PutV2ActivitiesActivityRecordsRecordIDMissingValueErrorData(BaseModel):
    status_code: float
    type: models_put_v2_activities_activity_records_record_id_op.PutV2ActivitiesActivityRecordsRecordIDBadRequestType
    code: models_put_v2_activities_activity_records_record_id_op.PutV2ActivitiesActivityRecordsRecordIDCodeMissingValue
    message: str


@dataclass(unsafe_hash=True)
class PutV2ActivitiesActivityRecordsRecordIDMissingValueError(SDKError):
    r"""Bad Request"""

    data: PutV2ActivitiesActivityRecordsRecordIDMissingValueErrorData = field(
        hash=False
    )

    def __init__(
        self,
        data: PutV2ActivitiesActivityRecordsRecordIDMissingValueErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
