"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from attio import errors, models, utils
from attio._hooks import HookContext
from attio.types import OptionalNullable, UNSET
from attio.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Dict, Iterable, List, Mapping, Optional, Union


class ActivityRecords(BaseSDK):
    def post_v2_activities_activity_records_query(
        self,
        *,
        activity: str,
        filter_: Optional[Mapping[str, Any]] = None,
        sorts: Optional[
            Union[
                Iterable[models.PostV2ActivitiesActivityRecordsQuerySortUnion],
                Iterable[models.PostV2ActivitiesActivityRecordsQuerySortUnionTypedDict],
            ]
        ] = None,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PostV2ActivitiesActivityRecordsQueryResponse:
        r"""List activity records

        Lists activity records, with the option to filter and sort results.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read`, `activity_configuration:read`.

        :param activity:
        :param filter_: An object used to filter results to a subset of results. Cannot be used together with `filter_view_id`. See the [full guide to filtering and sorting here](/rest-api/guides/filtering-and-sorting).
        :param sorts: An object used to sort results. See the [full guide to filtering and sorting here](/rest-api/guides/filtering-and-sorting).
        :param limit: The maximum number of results to return. Defaults to 500. See the [full guide to pagination here](/rest-api/guides/pagination).
        :param offset: The number of results to skip over before returning. Defaults to 0. See the [full guide to pagination here](/rest-api/guides/pagination).
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PostV2ActivitiesActivityRecordsQueryRequest(
            activity=activity,
            request_body=models.PostV2ActivitiesActivityRecordsQueryRequestBody(
                filter_=utils.unmarshal(filter_, Optional[Dict[str, Any]]),
                sorts=utils.get_pydantic_model(
                    sorts,
                    Optional[
                        List[models.PostV2ActivitiesActivityRecordsQuerySortUnion]
                    ],
                ),
                limit=limit,
                offset=offset,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/v2/activities/{activity}/records/query",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.PostV2ActivitiesActivityRecordsQueryRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="post_/v2/activities/{activity}/records/query",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.PostV2ActivitiesActivityRecordsQueryResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.PostV2ActivitiesActivityRecordsQueryFilterErrorData, http_res
            )
            raise errors.PostV2ActivitiesActivityRecordsQueryFilterError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.PostV2ActivitiesActivityRecordsQueryNotFoundErrorData, http_res
            )
            raise errors.PostV2ActivitiesActivityRecordsQueryNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def post_v2_activities_activity_records_query_async(
        self,
        *,
        activity: str,
        filter_: Optional[Mapping[str, Any]] = None,
        sorts: Optional[
            Union[
                Iterable[models.PostV2ActivitiesActivityRecordsQuerySortUnion],
                Iterable[models.PostV2ActivitiesActivityRecordsQuerySortUnionTypedDict],
            ]
        ] = None,
        limit: Optional[float] = None,
        offset: Optional[float] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PostV2ActivitiesActivityRecordsQueryResponse:
        r"""List activity records

        Lists activity records, with the option to filter and sort results.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read`, `activity_configuration:read`.

        :param activity:
        :param filter_: An object used to filter results to a subset of results. Cannot be used together with `filter_view_id`. See the [full guide to filtering and sorting here](/rest-api/guides/filtering-and-sorting).
        :param sorts: An object used to sort results. See the [full guide to filtering and sorting here](/rest-api/guides/filtering-and-sorting).
        :param limit: The maximum number of results to return. Defaults to 500. See the [full guide to pagination here](/rest-api/guides/pagination).
        :param offset: The number of results to skip over before returning. Defaults to 0. See the [full guide to pagination here](/rest-api/guides/pagination).
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PostV2ActivitiesActivityRecordsQueryRequest(
            activity=activity,
            request_body=models.PostV2ActivitiesActivityRecordsQueryRequestBody(
                filter_=utils.unmarshal(filter_, Optional[Dict[str, Any]]),
                sorts=utils.get_pydantic_model(
                    sorts,
                    Optional[
                        List[models.PostV2ActivitiesActivityRecordsQuerySortUnion]
                    ],
                ),
                limit=limit,
                offset=offset,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/v2/activities/{activity}/records/query",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.PostV2ActivitiesActivityRecordsQueryRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="post_/v2/activities/{activity}/records/query",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.PostV2ActivitiesActivityRecordsQueryResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.PostV2ActivitiesActivityRecordsQueryFilterErrorData, http_res
            )
            raise errors.PostV2ActivitiesActivityRecordsQueryFilterError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.PostV2ActivitiesActivityRecordsQueryNotFoundErrorData, http_res
            )
            raise errors.PostV2ActivitiesActivityRecordsQueryNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    def post_v2_activities_activity_records(
        self,
        *,
        activity: str,
        data: Union[
            models.PostV2ActivitiesActivityRecordsDataRequest,
            models.PostV2ActivitiesActivityRecordsDataRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PostV2ActivitiesActivityRecordsResponse:
        r"""Create an activity record

        Creates a new activity record, for example one specific phone call.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read-write`, `activity_configuration:read`.

        :param activity:
        :param data:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PostV2ActivitiesActivityRecordsRequest(
            activity=activity,
            request_body=models.PostV2ActivitiesActivityRecordsRequestBody(
                data=utils.get_pydantic_model(
                    data, models.PostV2ActivitiesActivityRecordsDataRequest
                ),
            ),
        )

        req = self._build_request(
            method="POST",
            path="/v2/activities/{activity}/records",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.PostV2ActivitiesActivityRecordsRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="post_/v2/activities/{activity}/records",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.PostV2ActivitiesActivityRecordsResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.ValueNotFoundErrorData, http_res
            )
            raise errors.ValueNotFoundError(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.PostV2ActivitiesActivityRecordsUnauthorizedErrorData, http_res
            )
            raise errors.PostV2ActivitiesActivityRecordsUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.PostV2ActivitiesActivityRecordsNotFoundErrorData, http_res
            )
            raise errors.PostV2ActivitiesActivityRecordsNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def post_v2_activities_activity_records_async(
        self,
        *,
        activity: str,
        data: Union[
            models.PostV2ActivitiesActivityRecordsDataRequest,
            models.PostV2ActivitiesActivityRecordsDataRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PostV2ActivitiesActivityRecordsResponse:
        r"""Create an activity record

        Creates a new activity record, for example one specific phone call.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read-write`, `activity_configuration:read`.

        :param activity:
        :param data:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PostV2ActivitiesActivityRecordsRequest(
            activity=activity,
            request_body=models.PostV2ActivitiesActivityRecordsRequestBody(
                data=utils.get_pydantic_model(
                    data, models.PostV2ActivitiesActivityRecordsDataRequest
                ),
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/v2/activities/{activity}/records",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.PostV2ActivitiesActivityRecordsRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="post_/v2/activities/{activity}/records",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.PostV2ActivitiesActivityRecordsResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.ValueNotFoundErrorData, http_res
            )
            raise errors.ValueNotFoundError(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.PostV2ActivitiesActivityRecordsUnauthorizedErrorData, http_res
            )
            raise errors.PostV2ActivitiesActivityRecordsUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.PostV2ActivitiesActivityRecordsNotFoundErrorData, http_res
            )
            raise errors.PostV2ActivitiesActivityRecordsNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    def get_v2_activities_activity_records_record_id_(
        self,
        *,
        activity: str,
        record_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetV2ActivitiesActivityRecordsRecordIDResponse:
        r"""Get an activity record

        Gets a single activity record by its `record_id`.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read`, `activity_configuration:read`.

        :param activity:
        :param record_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetV2ActivitiesActivityRecordsRecordIDRequest(
            activity=activity,
            record_id=record_id,
        )

        req = self._build_request(
            method="GET",
            path="/v2/activities/{activity}/records/{record_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_/v2/activities/{activity}/records/{record_id}",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.GetV2ActivitiesActivityRecordsRecordIDResponse, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetV2ActivitiesActivityRecordsRecordIDNotFoundErrorData, http_res
            )
            raise errors.GetV2ActivitiesActivityRecordsRecordIDNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def get_v2_activities_activity_records_record_id__async(
        self,
        *,
        activity: str,
        record_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetV2ActivitiesActivityRecordsRecordIDResponse:
        r"""Get an activity record

        Gets a single activity record by its `record_id`.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read`, `activity_configuration:read`.

        :param activity:
        :param record_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetV2ActivitiesActivityRecordsRecordIDRequest(
            activity=activity,
            record_id=record_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/activities/{activity}/records/{record_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_/v2/activities/{activity}/records/{record_id}",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.GetV2ActivitiesActivityRecordsRecordIDResponse, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetV2ActivitiesActivityRecordsRecordIDNotFoundErrorData, http_res
            )
            raise errors.GetV2ActivitiesActivityRecordsRecordIDNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    def patch_v2_activities_activity_records_record_id_(
        self,
        *,
        activity: str,
        record_id: str,
        data: Union[
            models.PatchV2ActivitiesActivityRecordsRecordIDDataRequest,
            models.PatchV2ActivitiesActivityRecordsRecordIDDataRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PatchV2ActivitiesActivityRecordsRecordIDResponse:
        r"""Update an activity record (append multiselect values)

        Use this endpoint to update activity records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the `PUT` endpoint to overwrite or remove multiselect attribute values.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read-write`, `activity_configuration:read`.

        :param activity:
        :param record_id:
        :param data:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PatchV2ActivitiesActivityRecordsRecordIDRequest(
            activity=activity,
            record_id=record_id,
            request_body=models.PatchV2ActivitiesActivityRecordsRecordIDRequestBody(
                data=utils.get_pydantic_model(
                    data, models.PatchV2ActivitiesActivityRecordsRecordIDDataRequest
                ),
            ),
        )

        req = self._build_request(
            method="PATCH",
            path="/v2/activities/{activity}/records/{record_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.PatchV2ActivitiesActivityRecordsRecordIDRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="patch_/v2/activities/{activity}/records/{record_id}",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.PatchV2ActivitiesActivityRecordsRecordIDResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.PatchV2ActivitiesActivityRecordsRecordIDMissingValueErrorData,
                http_res,
            )
            raise errors.PatchV2ActivitiesActivityRecordsRecordIDMissingValueError(
                response_data, http_res
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.PatchV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData,
                http_res,
            )
            raise errors.PatchV2ActivitiesActivityRecordsRecordIDUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.PatchV2ActivitiesActivityRecordsRecordIDNotFoundErrorData,
                http_res,
            )
            raise errors.PatchV2ActivitiesActivityRecordsRecordIDNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def patch_v2_activities_activity_records_record_id__async(
        self,
        *,
        activity: str,
        record_id: str,
        data: Union[
            models.PatchV2ActivitiesActivityRecordsRecordIDDataRequest,
            models.PatchV2ActivitiesActivityRecordsRecordIDDataRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PatchV2ActivitiesActivityRecordsRecordIDResponse:
        r"""Update an activity record (append multiselect values)

        Use this endpoint to update activity records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the `PUT` endpoint to overwrite or remove multiselect attribute values.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read-write`, `activity_configuration:read`.

        :param activity:
        :param record_id:
        :param data:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PatchV2ActivitiesActivityRecordsRecordIDRequest(
            activity=activity,
            record_id=record_id,
            request_body=models.PatchV2ActivitiesActivityRecordsRecordIDRequestBody(
                data=utils.get_pydantic_model(
                    data, models.PatchV2ActivitiesActivityRecordsRecordIDDataRequest
                ),
            ),
        )

        req = self._build_request_async(
            method="PATCH",
            path="/v2/activities/{activity}/records/{record_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.PatchV2ActivitiesActivityRecordsRecordIDRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="patch_/v2/activities/{activity}/records/{record_id}",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.PatchV2ActivitiesActivityRecordsRecordIDResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.PatchV2ActivitiesActivityRecordsRecordIDMissingValueErrorData,
                http_res,
            )
            raise errors.PatchV2ActivitiesActivityRecordsRecordIDMissingValueError(
                response_data, http_res
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.PatchV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData,
                http_res,
            )
            raise errors.PatchV2ActivitiesActivityRecordsRecordIDUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.PatchV2ActivitiesActivityRecordsRecordIDNotFoundErrorData,
                http_res,
            )
            raise errors.PatchV2ActivitiesActivityRecordsRecordIDNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    def put_v2_activities_activity_records_record_id_(
        self,
        *,
        activity: str,
        record_id: str,
        data: Union[
            models.PutV2ActivitiesActivityRecordsRecordIDDataRequest,
            models.PutV2ActivitiesActivityRecordsRecordIDDataRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PutV2ActivitiesActivityRecordsRecordIDResponse:
        r"""Update an activity record (overwrite multiselect values)

        Use this endpoint to update activity records by `record_id`. If the update payload includes multiselect attributes, the values supplied will overwrite/remove the list of values that already exist (if any). Use the `PATCH` endpoint to append multiselect values without removing those that already exist.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read-write`, `activity_configuration:read`.

        :param activity:
        :param record_id:
        :param data:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PutV2ActivitiesActivityRecordsRecordIDRequest(
            activity=activity,
            record_id=record_id,
            request_body=models.PutV2ActivitiesActivityRecordsRecordIDRequestBody(
                data=utils.get_pydantic_model(
                    data, models.PutV2ActivitiesActivityRecordsRecordIDDataRequest
                ),
            ),
        )

        req = self._build_request(
            method="PUT",
            path="/v2/activities/{activity}/records/{record_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.PutV2ActivitiesActivityRecordsRecordIDRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="put_/v2/activities/{activity}/records/{record_id}",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.PutV2ActivitiesActivityRecordsRecordIDResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.PutV2ActivitiesActivityRecordsRecordIDMissingValueErrorData,
                http_res,
            )
            raise errors.PutV2ActivitiesActivityRecordsRecordIDMissingValueError(
                response_data, http_res
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.PutV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData,
                http_res,
            )
            raise errors.PutV2ActivitiesActivityRecordsRecordIDUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.PutV2ActivitiesActivityRecordsRecordIDNotFoundErrorData, http_res
            )
            raise errors.PutV2ActivitiesActivityRecordsRecordIDNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def put_v2_activities_activity_records_record_id__async(
        self,
        *,
        activity: str,
        record_id: str,
        data: Union[
            models.PutV2ActivitiesActivityRecordsRecordIDDataRequest,
            models.PutV2ActivitiesActivityRecordsRecordIDDataRequestTypedDict,
        ],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PutV2ActivitiesActivityRecordsRecordIDResponse:
        r"""Update an activity record (overwrite multiselect values)

        Use this endpoint to update activity records by `record_id`. If the update payload includes multiselect attributes, the values supplied will overwrite/remove the list of values that already exist (if any). Use the `PATCH` endpoint to append multiselect values without removing those that already exist.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read-write`, `activity_configuration:read`.

        :param activity:
        :param record_id:
        :param data:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.PutV2ActivitiesActivityRecordsRecordIDRequest(
            activity=activity,
            record_id=record_id,
            request_body=models.PutV2ActivitiesActivityRecordsRecordIDRequestBody(
                data=utils.get_pydantic_model(
                    data, models.PutV2ActivitiesActivityRecordsRecordIDDataRequest
                ),
            ),
        )

        req = self._build_request_async(
            method="PUT",
            path="/v2/activities/{activity}/records/{record_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.request_body,
                False,
                False,
                "json",
                models.PutV2ActivitiesActivityRecordsRecordIDRequestBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="put_/v2/activities/{activity}/records/{record_id}",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.PutV2ActivitiesActivityRecordsRecordIDResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.PutV2ActivitiesActivityRecordsRecordIDMissingValueErrorData,
                http_res,
            )
            raise errors.PutV2ActivitiesActivityRecordsRecordIDMissingValueError(
                response_data, http_res
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.PutV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData,
                http_res,
            )
            raise errors.PutV2ActivitiesActivityRecordsRecordIDUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.PutV2ActivitiesActivityRecordsRecordIDNotFoundErrorData, http_res
            )
            raise errors.PutV2ActivitiesActivityRecordsRecordIDNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    def delete_v2_activities_activity_records_record_id_(
        self,
        *,
        activity: str,
        record_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DeleteV2ActivitiesActivityRecordsRecordIDResponse:
        r"""Delete an activity record

        Deletes a single activity record by its `record_id`.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read-write`, `activity_configuration:read`.

        :param activity:
        :param record_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeleteV2ActivitiesActivityRecordsRecordIDRequest(
            activity=activity,
            record_id=record_id,
        )

        req = self._build_request(
            method="DELETE",
            path="/v2/activities/{activity}/records/{record_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="delete_/v2/activities/{activity}/records/{record_id}",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.DeleteV2ActivitiesActivityRecordsRecordIDResponse, http_res
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.DeleteV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData,
                http_res,
            )
            raise errors.DeleteV2ActivitiesActivityRecordsRecordIDUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.DeleteV2ActivitiesActivityRecordsRecordIDNotFoundErrorData,
                http_res,
            )
            raise errors.DeleteV2ActivitiesActivityRecordsRecordIDNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def delete_v2_activities_activity_records_record_id__async(
        self,
        *,
        activity: str,
        record_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DeleteV2ActivitiesActivityRecordsRecordIDResponse:
        r"""Delete an activity record

        Deletes a single activity record by its `record_id`.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `activity_record:read-write`, `activity_configuration:read`.

        :param activity:
        :param record_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeleteV2ActivitiesActivityRecordsRecordIDRequest(
            activity=activity,
            record_id=record_id,
        )

        req = self._build_request_async(
            method="DELETE",
            path="/v2/activities/{activity}/records/{record_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="delete_/v2/activities/{activity}/records/{record_id}",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Activity records"],
                extensions={"x-hidden": True, "x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.DeleteV2ActivitiesActivityRecordsRecordIDResponse, http_res
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.DeleteV2ActivitiesActivityRecordsRecordIDUnauthorizedErrorData,
                http_res,
            )
            raise errors.DeleteV2ActivitiesActivityRecordsRecordIDUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.DeleteV2ActivitiesActivityRecordsRecordIDNotFoundErrorData,
                http_res,
            )
            raise errors.DeleteV2ActivitiesActivityRecordsRecordIDNotFoundError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)
