"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from attio import errors, models, utils
from attio._hooks import HookContext
from attio.types import OptionalNullable, UNSET
from attio.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional


class Emails(BaseSDK):
    r"""Emails are messages synced from connected mailboxes."""

    def get_v2_emails(
        self,
        *,
        limit: Optional[int] = 25,
        cursor: Optional[str] = None,
        linked_object: Optional[str] = None,
        linked_record_ids: Optional[str] = None,
        participants: Optional[str] = "",
        domain: Optional[str] = None,
        sent_after: OptionalNullable[str] = UNSET,
        sent_before: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetV2EmailsResponse:
        r"""List emails

        Lists email metadata from your workspace's connected mailboxes. Email content is never returned.

        At least one of `linked_object` with `linked_record_ids`, `participants`, or `domain` must be supplied; there is no way to list every email. When several are supplied they are combined with OR: emails matching any of the filters are returned.

        > **Requesting access:** this endpoint is enabled per workspace and per app while it is in alpha. Contact [support@attio.com](mailto:support@attio.com) to request access.

        **Things to know**

        - Filters that identify your own workspace are ignored. This covers a member's or invited member's address, one of your mailboxes, and any of their domains. If every filter you supply is ignored, an empty page is returned.
        - A filter that names a protected recipient in your workspace is rejected rather than ignored. This covers an address or a domain you supply directly. A record whose address or domain is a protected recipient is ignored instead, in the same way as the filters above.
        - Emails from a mailbox shared with your workspace as metadata only are returned without a subject line. An email is left out entirely when it has no participant you may see — that is, when every participant outside your workspace is a protected recipient.
        - An email that reached more than one of your mailboxes is returned once, and `id.mailbox_id` identifies whichever copy was readable.
        - `linked_records` is derived when you make the request rather than stored, so it reflects your records as they are now.
        - Emails are returned newest first, ordered by when they were sent. Each request scans a bounded number of emails, so a page can hold fewer emails than `limit`, or none at all, while more are still available. Keep paginating for as long as a `next_cursor` is returned, rather than stopping on a short page.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `email:read`, `record_permission:read`, `object_configuration:read`.

        :param limit:
        :param cursor:
        :param linked_object:
        :param linked_record_ids:
        :param participants:
        :param domain:
        :param sent_after:
        :param sent_before:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetV2EmailsRequest(
            limit=limit,
            cursor=cursor,
            linked_object=linked_object,
            linked_record_ids=linked_record_ids,
            participants=participants,
            domain=domain,
            sent_after=sent_after,
            sent_before=sent_before,
        )

        req = self._build_request(
            method="GET",
            path="/v2/emails",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_/v2/emails",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Emails"],
                extensions={"x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GetV2EmailsResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)

    async def get_v2_emails_async(
        self,
        *,
        limit: Optional[int] = 25,
        cursor: Optional[str] = None,
        linked_object: Optional[str] = None,
        linked_record_ids: Optional[str] = None,
        participants: Optional[str] = "",
        domain: Optional[str] = None,
        sent_after: OptionalNullable[str] = UNSET,
        sent_before: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetV2EmailsResponse:
        r"""List emails

        Lists email metadata from your workspace's connected mailboxes. Email content is never returned.

        At least one of `linked_object` with `linked_record_ids`, `participants`, or `domain` must be supplied; there is no way to list every email. When several are supplied they are combined with OR: emails matching any of the filters are returned.

        > **Requesting access:** this endpoint is enabled per workspace and per app while it is in alpha. Contact [support@attio.com](mailto:support@attio.com) to request access.

        **Things to know**

        - Filters that identify your own workspace are ignored. This covers a member's or invited member's address, one of your mailboxes, and any of their domains. If every filter you supply is ignored, an empty page is returned.
        - A filter that names a protected recipient in your workspace is rejected rather than ignored. This covers an address or a domain you supply directly. A record whose address or domain is a protected recipient is ignored instead, in the same way as the filters above.
        - Emails from a mailbox shared with your workspace as metadata only are returned without a subject line. An email is left out entirely when it has no participant you may see — that is, when every participant outside your workspace is a protected recipient.
        - An email that reached more than one of your mailboxes is returned once, and `id.mailbox_id` identifies whichever copy was readable.
        - `linked_records` is derived when you make the request rather than stored, so it reflects your records as they are now.
        - Emails are returned newest first, ordered by when they were sent. Each request scans a bounded number of emails, so a page can hold fewer emails than `limit`, or none at all, while more are still available. Keep paginating for as long as a `next_cursor` is returned, rather than stopping on a short page.

        This endpoint is in alpha and may be subject to breaking changes as we gather feedback.

        Required scopes: `email:read`, `record_permission:read`, `object_configuration:read`.

        :param limit:
        :param cursor:
        :param linked_object:
        :param linked_record_ids:
        :param participants:
        :param domain:
        :param sent_after:
        :param sent_before:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetV2EmailsRequest(
            limit=limit,
            cursor=cursor,
            linked_object=linked_object,
            linked_record_ids=linked_record_ids,
            participants=participants,
            domain=domain,
            sent_after=sent_after,
            sent_before=sent_before,
        )

        req = self._build_request_async(
            method="GET",
            path="/v2/emails",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_/v2/emails",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Emails"],
                extensions={"x-mint": {"metadata": {"tag": "ALPHA"}}},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.GetV2EmailsResponse, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.SDKDefaultError("API error occurred", http_res, http_res_text)

        raise errors.SDKDefaultError("Unexpected response received", http_res)
