workflowVersion: 1.0.0
sources:
  attio:
    inputs:
      - location: openapi/api-202610030405.json
    overlays:
      - location: overlay.yaml
    output: openapi/api-202610030405-overlay.json
    registry:
      location: registry.speakeasyapi.dev/elviskahoro/attio/attio
targets:
  attio:
    target: python
    source: attio
