"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ActivityIDTypedDict(TypedDict):
    workspace_id: str
    r"""A UUID to identify the workspace this activity belongs to."""
    activity_id: str
    r"""A UUID to identify the activity."""


class ActivityID(BaseModel):
    workspace_id: str
    r"""A UUID to identify the workspace this activity belongs to."""

    activity_id: str
    r"""A UUID to identify the activity."""


class ExtendTypedDict(TypedDict):
    schema_id: str
    r"""A UUID to identify the schema."""
    schema_slug: str
    r"""The human-readable slug of the schema."""


class Extend(BaseModel):
    schema_id: str
    r"""A UUID to identify the schema."""

    schema_slug: str
    r"""The human-readable slug of the schema."""


class ActivityTypedDict(TypedDict):
    id: ActivityIDTypedDict
    api_slug: str
    r"""A unique, human-readable slug to access the activity through URLs and API calls. Formatted in snake case."""
    singular_noun: str
    r"""The singular form of the activity's name."""
    plural_noun: str
    r"""The plural form of the activity's name."""
    extends: List[ExtendTypedDict]
    r"""The schemas this activity directly extends, which supply its inherited attributes."""
    is_system_activity: bool
    r"""`true` when Attio defines the activity, `false` when it's a custom activity."""
    created_at: str
    r"""When the activity was created."""


class Activity(BaseModel):
    id: ActivityID

    api_slug: str
    r"""A unique, human-readable slug to access the activity through URLs and API calls. Formatted in snake case."""

    singular_noun: str
    r"""The singular form of the activity's name."""

    plural_noun: str
    r"""The plural form of the activity's name."""

    extends: List[Extend]
    r"""The schemas this activity directly extends, which supply its inherited attributes."""

    is_system_activity: bool
    r"""`true` when Attio defines the activity, `false` when it's a custom activity."""

    created_at: str
    r"""When the activity was created."""
