"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .status import Status, StatusTypedDict
from attio.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from attio.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


PatchV2TargetIdentifierAttributesAttributeStatusesStatusTarget = Literal[
    "lists",
    "objects",
]
r"""Whether the attribute is on an object or a list."""


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusDataTypedDict(TypedDict):
    title: NotRequired[str]
    r"""The Title of the status"""
    celebration_enabled: NotRequired[bool]
    r"""Whether arriving at this status triggers a celebration effect"""
    target_time_in_status: NotRequired[Nullable[str]]
    r"""Target time for a record to spend in given status expressed as a ISO-8601 duration string"""
    is_archived: NotRequired[bool]
    r"""Whether or not to archive the status. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving."""


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusData(BaseModel):
    title: Optional[str] = None
    r"""The Title of the status"""

    celebration_enabled: Optional[bool] = False
    r"""Whether arriving at this status triggers a celebration effect"""

    target_time_in_status: OptionalNullable[str] = UNSET
    r"""Target time for a record to spend in given status expressed as a ISO-8601 duration string"""

    is_archived: Optional[bool] = None
    r"""Whether or not to archive the status. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["title", "celebration_enabled", "target_time_in_status", "is_archived"]
        )
        nullable_fields = set(["target_time_in_status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusRequestBodyTypedDict(
    TypedDict
):
    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusDataTypedDict


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusRequestBody(BaseModel):
    data: PatchV2TargetIdentifierAttributesAttributeStatusesStatusData


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusRequestTypedDict(
    TypedDict
):
    target: PatchV2TargetIdentifierAttributesAttributeStatusesStatusTarget
    r"""Whether the attribute is on an object or a list."""
    identifier: str
    attribute: str
    status: str
    request_body: (
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusRequestBodyTypedDict
    )


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusRequest(BaseModel):
    target: Annotated[
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusTarget,
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Whether the attribute is on an object or a list."""

    identifier: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    attribute: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    status: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


PatchV2TargetIdentifierAttributesAttributeStatusesStatusConflictType = Literal[
    "invalid_request_error",
]


PatchV2TargetIdentifierAttributesAttributeStatusesStatusCodeSlugConflict = Literal[
    "slug_conflict",
]


PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundType = Literal[
    "invalid_request_error",
]


PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundCode = Literal[
    "not_found",
]


PatchV2TargetIdentifierAttributesAttributeStatusesStatusForbiddenType = Literal[
    "auth_error",
]


PatchV2TargetIdentifierAttributesAttributeStatusesStatusCodeUnauthorized = Literal[
    "unauthorized",
]


PatchV2TargetIdentifierAttributesAttributeStatusesStatusBadRequestType = Literal[
    "invalid_request_error",
]


PatchV2TargetIdentifierAttributesAttributeStatusesStatusBadRequestCode = Literal[
    "value_not_found",
    "validation_type",
]


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusResponseTypedDict(
    TypedDict
):
    r"""Success"""

    data: StatusTypedDict


class PatchV2TargetIdentifierAttributesAttributeStatusesStatusResponse(BaseModel):
    r"""Success"""

    data: Status
