"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .note import Note, NoteTypedDict
from attio.types import BaseModel, UNSET_SENTINEL
from attio.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


PatchV2NotesNoteIDFormat = Literal[
    "plaintext",
    "markdown",
]
r"""Specify the format for the note's content. Choose from:
- `plaintext`: Standard text format where `\n` signifies a new line.
- `markdown`: Enables rich text formatting using a subset of Markdown syntax:
- **Headings**: Levels 1-3 (`#`, `##`, `###`).
- **Lists**: Unordered (`-`, `*`, `+`) and ordered (`1.`, `2.`).
- **Text styles**: Bold (`**bold**` or `__bold__`), italic (`*italic*` or `_italic_`), strikethrough (`~~strikethrough~~`), and highlight (`==highlighted==`).
- **Links**: Standard Markdown links (`[link text](https://example.com)`).

*Note: While the Attio interface supports image embeds, they cannot currently be added or retrieved via the API's markdown format.*
"""


class PatchV2NotesNoteIDDataTypedDict(TypedDict):
    title: NotRequired[str]
    r"""The note title. The title is plaintext only and has no formatting."""
    format_: NotRequired[PatchV2NotesNoteIDFormat]
    r"""Specify the format for the note's content. Choose from:
    - `plaintext`: Standard text format where `\n` signifies a new line.
    - `markdown`: Enables rich text formatting using a subset of Markdown syntax:
    - **Headings**: Levels 1-3 (`#`, `##`, `###`).
    - **Lists**: Unordered (`-`, `*`, `+`) and ordered (`1.`, `2.`).
    - **Text styles**: Bold (`**bold**` or `__bold__`), italic (`*italic*` or `_italic_`), strikethrough (`~~strikethrough~~`), and highlight (`==highlighted==`).
    - **Links**: Standard Markdown links (`[link text](https://example.com)`).

    *Note: While the Attio interface supports image embeds, they cannot currently be added or retrieved via the API's markdown format.*
    """
    content: NotRequired[str]
    r"""The main content of the note, formatted according to the value provided in the `format` field. Use `\n` for line breaks in `plaintext`. For `markdown`, utilize the supported syntax elements to structure and style your note."""


class PatchV2NotesNoteIDData(BaseModel):
    title: Optional[str] = None
    r"""The note title. The title is plaintext only and has no formatting."""

    format_: Annotated[
        Optional[PatchV2NotesNoteIDFormat], pydantic.Field(alias="format")
    ] = None
    r"""Specify the format for the note's content. Choose from:
    - `plaintext`: Standard text format where `\n` signifies a new line.
    - `markdown`: Enables rich text formatting using a subset of Markdown syntax:
    - **Headings**: Levels 1-3 (`#`, `##`, `###`).
    - **Lists**: Unordered (`-`, `*`, `+`) and ordered (`1.`, `2.`).
    - **Text styles**: Bold (`**bold**` or `__bold__`), italic (`*italic*` or `_italic_`), strikethrough (`~~strikethrough~~`), and highlight (`==highlighted==`).
    - **Links**: Standard Markdown links (`[link text](https://example.com)`).

    *Note: While the Attio interface supports image embeds, they cannot currently be added or retrieved via the API's markdown format.*
    """

    content: Optional[str] = None
    r"""The main content of the note, formatted according to the value provided in the `format` field. Use `\n` for line breaks in `plaintext`. For `markdown`, utilize the supported syntax elements to structure and style your note."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "format", "content"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PatchV2NotesNoteIDRequestBodyTypedDict(TypedDict):
    data: PatchV2NotesNoteIDDataTypedDict


class PatchV2NotesNoteIDRequestBody(BaseModel):
    data: PatchV2NotesNoteIDData


class PatchV2NotesNoteIDRequestTypedDict(TypedDict):
    note_id: str
    request_body: PatchV2NotesNoteIDRequestBodyTypedDict


class PatchV2NotesNoteIDRequest(BaseModel):
    note_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        PatchV2NotesNoteIDRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


PatchV2NotesNoteIDRequestEntityTooLargeType = Literal["invalid_request_error",]


PatchV2NotesNoteIDRequestEntityTooLargeCode = Literal["validation_type",]


PatchV2NotesNoteIDNotFoundType = Literal["invalid_request_error",]


PatchV2NotesNoteIDNotFoundCode = Literal["not_found",]


class PatchV2NotesNoteIDResponseTypedDict(TypedDict):
    r"""Success"""

    data: NoteTypedDict


class PatchV2NotesNoteIDResponse(BaseModel):
    r"""Success"""

    data: Note


try:
    PatchV2NotesNoteIDData.model_rebuild()
except NameError:
    pass
